apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2esb
  labels:
    name: wso2esb
spec:
  replicas: 3
  selector:
    name: wso2esb
  template:
    metadata:
      labels:
        name: wso2esb
    spec:
      containers:
      - name: wso2esb
        image: imesh/wso2esb:4.8.1
        env:
        -
          name: CONFIG_PARAM_CLUSTERING
          value: 'true'
        -
          name: CONFIG_PARAM_MEMBERSHIP_SCHEME
          value: kubernetes
        - 
          name: KUBERNETES_MASTER
          value: http://172.17.8.101:8080
        - 
          name: KUBERNETES_NAMESPACE
          value: default
        -
          name: KUBERNETES_SERVICES
          value: wso2esb
        ports:
        - containerPort: 9443
