apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: wso2esb
  name: wso2esb
spec: 
  ports:
    # the port that this service should serve on
    - port: 9443
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: wso2esb
