apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        resources:
        limits :
          cpu: 0.5
        env:
        -
          name: MYSQL_ROOT_PASSWORD
          value: mysql
        ports:
        - containerPort: 3306
